version: '3'
services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
   